title: Andrew McAllister 
description: Personal website for Andrew McAllister

url: http://mcallister.science
paginate_path: "blog/page:num/"
permalink: :title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: mcala
   twitter: McAllisterSci
   facebook: 
   email: andrew@mcallister.science

google_analytics: "UA-112472855-1"
