title: Andrew McAllister
description: Andrew McAllister's personal website.

url: https://mcallister.science
paginate_path: "blog/page:num/"
permalink: :title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

collections:
  bibs:
    output: true
    permalink: /:collection/:name


navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: mcala
   twitter: McAllisterSci
   facebook: mcallistersci
   email: andrew@mcallister.science

google_analytics: "UA-112472855-1"

scholar:
  style: assets/apa.csl
  locale: en
  source: ./_bibliography
  use_raw_bibtex_entry: true
  sort_by: author
  order: ascending
  bibtex_filters:
    - href
